version: '3.9'

services:

  clientsocket:
    build: 
      context: socket
      dockerfile: Dockerfile
    image: pyfi/clientsocket:latest
    container_name: clientsocket
    ports:
      - 3003:3003

  globalsocket:
    build: 
      context: docker/websockets
      dockerfile: Dockerfile
    image: pyfi/websockets:latest
    container_name: globalsocket
    environment:
      - PYFI_CHANNEL=global
    ports:
      - 3009:3000

  websockets2:
    build: 
      context: docker/websockets
      dockerfile: Dockerfile
    image: pyfi/websockets:latest
    container_name: websockets2
    environment:
      - PYFI_CHANNEL=proc2.task
    ports:
      - 3002:3000

  websockets:
    build: 
      context: docker/websockets
      dockerfile: Dockerfile
    image: pyfi/websockets:latest
    container_name: websockets
    environment:
      - PYFI_CHANNEL=proc1.task
    ports:
      - 3000:3000

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
      restart: unless-stopped
      ports:
        - 3001:3000

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - 8083:8083
      - 8086:8086
      - 8088:8088
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=pyfi
      - DOCKER_INFLUXDB_INIT_BUCKET=pyfi
    volumes:
      - influxdb_data:/var/lib/influxdb2

  processor:
    build: 
      context: .
      dockerfile: docker/Dockerfile.processor
    container_name: processor
    image: pyfi/processor:latest
    environment: 
      - "EVENTS=events"

  api:
    build: 
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    image: api:latest
    environment: 
      - "EVENTS=events"
    ports:
      - 8014:8003
    profiles: 
      - api
    depends_on:
      - redis
      - postgres
    volumes:
      - ./conf/supervisord-agent.conf:/etc/supervisor/conf.d/supervisord.conf

  agent3.docker:
    container_name: agent3.docker
    hostname: agent3
    image: elasticcode/agent:latest
    environment: 
      - "EVENTS=events"
    command:  "runuser -u pyfi -- /opt/pyfi/venv/bin/flow --debug -i /home/pyfi/pyfi.ini agent start -n agent3 --clean --size 20 --user pyfi --cpus 5"
    ports:
      - 8004:8002
    profiles: 
      - agent
    depends_on:
      - redis
      - postgres
      - rabbitmq
    volumes:
      - ./conf/supervisord-agent.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./conf/pyfi.ini:/home/pyfi/pyfi.ini
      - ./conf/pyfi.polar:/home/pyfi/pyfi.polar

  agent3:
    build: 
      context: .
      dockerfile: docker/Dockerfile.agent
    container_name: agent3
    hostname: agent3
    image: agent:latest
    environment: 
      - "EVENTS=events"
    command:  "runuser -u pyfi -- /opt/pyfi/venv/bin/flow --debug -i /home/pyfi/pyfi.ini agent start -n agent3 --clean --size 20 --user pyfi --cpus 5"
    ports:
      - 8004:8002
    profiles: 
      - agent
    depends_on:
      - redis
      - postgres
      - rabbitmq
    volumes:
      - ./conf/supervisord-agent.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./conf/pyfi.ini:/home/pyfi/pyfi.ini
      - ./conf/pyfi.polar:/home/pyfi/pyfi.polar

  agent2:
    build: 
      context: .
      dockerfile: docker/Dockerfile.agent
    container_name: agent2
    hostname: agent2
    image: agent:latest
    environment: 
      - "EVENTS=events"
    command:  "runuser -u pyfi -- /opt/pyfi/venv/bin/flow --debug -i /home/pyfi/pyfi.ini agent start -n agent2 --clean --size 20 --user pyfi --cpus 4"
    ports:
      - 8003:8002
    profiles: 
      - agent
    depends_on:
      - redis
      - postgres
      - rabbitmq
    volumes:
      - ./conf/supervisord-agent.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./conf/pyfi.ini:/home/pyfi/pyfi.ini
      - ./conf/pyfi.polar:/home/pyfi/pyfi.polar


  # http://localhost:5001
  logs:
    build:
      context: .
      dockerfile: docker/Dockerfile.logs
    container_name: logs
    image: logs:latest

  # http://localhost:8008
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 8008:80

  # Console - http://localhost:8888
  flower:  
    image: mher/flower:latest
    container_name: flower
    hostname: flower
    environment:
      - CELERY_BROKER_URL=pyamqp://rabbitmq
      - CELERY_ACCEPT_CONTENT=['json']
      - CELERY_TASK_SERIALIZER='json'
      - CELERY_RESULT_SERIALIZER='json'
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888  

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./app/dist/spa:/var/share/html
      - ./conf/mime.types:/etc/nginx/conf/mime.types
      - ./logs:/etc/nginx/logs
    depends_on:
      - rabbitmq
      - rabbitmq2
    ports:
      - 80:80
      - 443:443
      #- 15672:15672
      #- 5672:5672
      #- 5671:5671
      #- 4369:4369

  # Admin UI - http://localhost:15672/
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management
    restart: always
    volumes: 
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./data:/var/lib/rabbitmq/mnesia/
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - CLUSTERED=true
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 4369:4369

  rabbitmq2:
    container_name: rabbitmq2
    hostname: rabbitmq2
    image: rabbitmq:management
    volumes: 
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./conf/rabbit-cluster.sh:/tmp/rabbit-cluster.sh
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "15673:15672"

  postgres:
    container_name: postgres
    image: edoburu/pgbouncer:latest
    hostname: postgres
    environment:
       - DB_USER=postgres
       - DB_PASSWORD=pyfi101
       - DB_HOST=postgresdb
       - POOL_MODE=session
       - DB_NAME=pyfi 
       - LISTEN_PORT=6432
       - AUTH_TYPE=trust
       - CONN_MAX_AGE = 60
       - ADMIN_USERS=postgres
    ports:
      - "6432:6432"
    depends_on:
      - postgresdb
    volumes:
      - ./conf/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini

  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    hostname: postgresdb
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pyfi101
      POSTGRES_DB: pyfi
    ports:
      - "5434:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - ./conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6

  redis:
    container_name: redis
    hostname: redis
    image: redislabs/redismod  #redis:6.2.6
    restart: always
    ports:
      - 6379:6379

  # http://localhost:8001
  insights:
    container_name: insights
    depends_on: 
      - redis
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    #volumes:
    #  - ./data/redisinsight:/db

  mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  pgdata:
  influxdb_data:
    driver: local
  grafana_data: {}
