version: '3.9'

services:

  clientsocket:
    build:
      context: socket
      dockerfile: Dockerfile
    image: 013035288901.dkr.ecr.us-east-1.amazonaws.com/clientsocket:production
    container_name: clientsocket
    ports:
      - 3003:3003

  globalsocket:
    build:
      context: docker/websockets
      dockerfile: Dockerfile
    image: pyfi/websockets:production
    container_name: globalsocket
    environment:
      - PYFI_CHANNEL=global
    ports:
      - 3009:3000

  websockets2:
    build:
      context: docker/websockets
      dockerfile: Dockerfile
    image: pyfi/websockets:production
    container_name: websockets2
    environment:
      - PYFI_CHANNEL=proc2.task
    ports:
      - 3002:3000

  websockets:
    build:
      context: docker/websockets
      dockerfile: Dockerfile
    image: pyfi/websockets:production
    container_name: websockets
    environment:
      - PYFI_CHANNEL=proc1.task
    ports:
      - 3000:3000

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
        - GF_USERS_ALLOW_SIGN_UP=false
      restart: unless-stopped
      ports:
        - 3001:3000

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: api
    image: 013035288901.dkr.ecr.us-east-1.amazonaws.com/api:production
    environment:
      - "EVENTS=events"
      - "CB_KEY=test_cd3cu6vRcuyFScdCW8W8Y3QU1HmrVZ7AaXEm"
      - "CB_SITE=elasticcode-test"
      - "AUTH0_DOMAIN=elasticcode.us.auth0.com"
      - "API_AUDIENCE=https://app.elasticcode.ai/"
      - "API_HOST=api.elasticcode.ai"
    ports:
      - 8000:8003
    profiles:
      - api
    depends_on:
      - redis
      - postgresdb
    volumes:
      - /tmp:/tmp
      - ./conf/supervisord-agent.conf:/etc/supervisor/conf.d/supervisord.conf
      - /var/run/docker.sock:/var/run/docker.sock

  logs:
    build:
      context: .
      dockerfile: docker/Dockerfile.logs
    container_name: logs
    image: logs:latest

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - 8008:80

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management
    restart: always
    volumes:
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./data:/var/lib/rabbitmq/mnesia/
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - CLUSTERED=true
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 4369:4369

  rabbitmq2:
    container_name: rabbitmq2
    hostname: rabbitmq2
    image: rabbitmq:management
    volumes:
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./conf/rabbit-cluster.sh:/tmp/rabbit-cluster.sh
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq
      - RAM_NODE=true
    ports:
      - "5673:5672"
      - "15673:15672"

  postgresdb:
    container_name: postgresdb
    image: postgres:14
    hostname: postgresdb
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pyfi101
      POSTGRES_DB: pyfi
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - ./conf/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6

  redis:
    container_name: redis
    hostname: redis
    image: redislabs/redismod  #redis:6.2.6
    restart: always
    ports:
      - 6379:6379

  insights:
    container_name: insights
    depends_on:
      - redis
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001

  mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

  web:
    image: elasticcode/web:production
    container_name: web
    build:
      context: /home/darren/git/elasticcode-web
    ports:
      - 8443:443
      - 8180:80

  nginx:
    image: 013035288901.dkr.ecr.us-east-1.amazonaws.com/nginx:production
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: nginx
    volumes:
      - ./certs:/etc/nginx/certs
      - ./conf/mime.types:/etc/nginx/conf/mime.types
      - ./logs:/etc/nginx/logs
    depends_on:
      - rabbitmq
      - rabbitmq2
      - clientsocket
      - api
    links:
      - clientsocket
      - rabbitmq2
      - rabbitmq
      - api
    ports:
      - 80:80
      - 443:443

volumes:
  mongodb_data_container:
  pgdata:
  influxdb_data:
    driver: local
  grafana_data: {}
