version: '3.9'

services:
  nginx:
    image: 013035288901.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/dist/spa:/var/share/html
      - ./conf/mime.types:/etc/nginx/conf/mime.types
      - ./logs:/etc/nginx/logs
    ports:
      - 80:80
      - 443:443