version: '3.9'

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always
    volumes: 
      - ./conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
      - 4369:4369

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pyfi101
      POSTGRES_DB: pyfi
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 6


  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata:
