version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: mkdir ./certs
      - run: echo "$elasticcode_crt" > ./certs/elasticcode.crt
      - run: echo "$elasticcodeapp_crt" > ./certs/elasticcode-app.crt
      - run: echo "$elasticcode_key" > ./certs/elasticcode.key
      - run: ls -l ./certs
      - node/install:
          install-yarn: true
          node-version: '14.18.1'
      - run: npm install -g --force @quasar/cli@1.3.2  @quasar/app@2.4.3 quasar@1.22.1  @quasar/extras@1.15.5 @quasar/quasar-app-extension-qmarkdown@1.4.4
      - run: npm update -g @quasar/cli
      - persist_to_workspace:
           root: certs
           paths:
             - elasticcode.crt
             - elasticcode-app.crt
             - elasticcode.key
      - run:
          name: APT update
          command: 'sudo apt update'
      - run:
          name: Install Gevent
          command: 'pip install gevent'
      - run:
            name: Installing g++
            command: 'sudo apt install -y python3-gevent libev-dev build-essential'
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install UI
          command: make install-ui
      - run:
          name: Build UI
          command: make ui
      - persist_to_workspace:
          root: spa
          paths:
            - ./ui/dist/spa
      - run:
          name: Run tests
          command: make test

workflows:
  build-and-push:
    jobs:
      - build-and-test
      - aws-ecr/build-and-push-image:
          requires:
            - build-and-test
          attach-workspace: true
          workspace-root: certs
          aws-cli-version: latest
          create-repo: true
          dockerfile: Dockerfile.nginx.prod
          extra-build-args: '--compress'
          path: ./docker
          platform: linux/amd64
          public-registry: false
          push-image: true
          repo: nginx
          repo-scan-on-push: true
          tag: 'latest'
      - aws-ecr/build-and-push-image:
          requires:
            - build-and-test
          attach-workspace: true
          workspace-root: certs
          aws-cli-version: latest
          create-repo: true
          dockerfile: Dockerfile.api
          extra-build-args: '--compress'
          path: ./docker
          platform: linux/amd64
          public-registry: false
          push-image: true
          repo: api
          repo-scan-on-push: true
          tag: 'latest'