version: 2.1

orbs:
  python: circleci/python@1.5.0
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run: mkdir -p ./workspace/certs
      - run: echo "$elasticcode_crt" > ./workspace/certs/elasticcode.crt
      - run: echo "$elasticcode_app_crt" > ./workspace/certs/elasticcode-app.crt
      - run: echo "$elasticcode_key" > ./workspace/certs/elasticcode.key
      - run: ls -l ./workspace/certs
      - node/install:
          node-version: '14.18.1'
      - run: npm install -g --force @quasar/cli@1.3.2  @quasar/app@2.4.3 quasar@1.22.1  @quasar/extras@1.15.5 @quasar/quasar-app-extension-qmarkdown@1.4.4
      - run: npm update -g @quasar/cli
      - persist_to_workspace:
           root: workspace
           paths:
             - certs/elasticcode.crt
             - certs/elasticcode-app.crt
             - certs/elasticcode.key
      - run:
          name: APT update
          command: 'sudo apt update'
      - run:
          name: Install Gevent
          command: 'pip install gevent'
      - run:
            name: Installing g++
            command: 'sudo apt install -y python3-gevent libev-dev build-essential'
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install UI
          command: make install-ui
      - run:
          name: Build UI
          command: make ui
      - run:
          name: Copy UI
          command: mkdir -p workspace/ui/dist/spa; cp -r ui/dist/spa/* workspace/ui/dist/spa/
      - persist_to_workspace:
          root: workspace
          paths:
            - ui/dist/spa
      - run:
          name: Run tests
          command: make test

workflows:
  build-and-push:
    jobs:
      - build-and-test
      - aws-ecr/build-and-push-image:
          name: build-nginx
          requires:
            - build-and-test
          attach-workspace: true
          workspace-root: workspace
          aws-cli-version: latest
          create-repo: true
          dockerfile: Dockerfile.nginx
          extra-build-args: '--compress'
          path: ./docker
          platform: linux/amd64
          public-registry: false
          push-image: true
          repo: nginx
          repo-scan-on-push: true
          tag: 'develop'
          post-steps:
              - aws-ecr/tag-image:
                  repo: nginx
                  source-tag: 'develop'
                  target-tag: $CIRCLE_BUILD_NUM
      - aws-ecr/build-and-push-image:
          name: build-api
          requires:
            - build-and-test
          attach-workspace: true
          workspace-root: certs
          aws-cli-version: latest
          create-repo: true
          dockerfile: Dockerfile.api
          extra-build-args: '--compress'
          path: ./docker
          platform: linux/amd64
          public-registry: false
          push-image: true
          repo: api
          repo-scan-on-push: true
          tag: 'develop'
          post-steps:
              - aws-ecr/tag-image:
                  repo: api
                  source-tag: 'develop'
                  target-tag: $CIRCLE_BUILD_NUM
      - aws-ecr/build-and-push-image:
          name: build-socket
          requires:
            - build-and-test
          attach-workspace: true
          aws-cli-version: latest
          create-repo: true
          context: ./socket
          dockerfile: Dockerfile.dev
          extra-build-args: '--compress'
          path: ./socket
          platform: linux/amd64
          public-registry: false
          push-image: true
          repo: clientsocket
          repo-scan-on-push: true
          tag: 'develop'
          post-steps:
              - aws-ecr/tag-image:
                  repo: clientsocket
                  source-tag: 'develop'
                  target-tag: $CIRCLE_BUILD_NUM