FROM nginx:alpine

ADD ./conf/nginx.conf.prod /etc/nginx/nginx.conf
ADD ./conf/mime.types /etc/nginx/conf/mime.types
ADD ./workspace/certs /etc/nginx/certs
ADD ./conf/elasticcode /etc/nginx/sites-enabled/elasticcode
ARG COMMIT=None

COPY ./workspace/ui/dist/spa /var/share/html
ENV COMMIT=$COMMIT
RUN echo $COMMIT"|" >/var/share/html/commit
RUN date >>/var/share/html/commit
