FROM nginx@sha256:2e776a66a3556f001aba13431b26e448fe8acba277bf93d2ab1a785571a46d90

ADD ./conf/nginx.conf /etc/nginx/nginx.conf
ADD ./conf/mime.types /etc/nginx/conf/mime.types
ADD ./certs /etc/nginx/certs
ADD ./conf/elasticcode /etc/nginx/sites-enabled/elasticcode
ADD ./ui/dist/spa /var/share/html
ARG COMMIT=None
ARG BUILD_URL=None
ARG REPO_URL=None

ENV COMMIT=$COMMIT
ENV BUILD_URL=$BUILD_URL
RUN echo $COMMIT"|" >/var/share/html/commit
RUN date >>/var/share/html/commit
RUN echo "|" >>/var/share/html/commit
RUN echo $BUILD_URL"|" >>/var/share/html/commit
RUN echo $REPO_URL >>/var/share/html/commit