FROM nginx:1.25.0-alpine

ADD ./conf/nginx.conf /etc/nginx/nginx.conf
ADD ./conf/mime.types /etc/nginx/conf/mime.types
ADD ./workspace/certs /etc/nginx/certs
ADD ./conf/elasticcode /etc/nginx/sites-enabled/elasticcode
ARG COMMIT=None
ARG BUILD_URL=None
ARG REPO_URL=None

COPY ./workspace/ui/dist/spa /var/share/html
ENV COMMIT=$COMMIT
ENV BUILD_URL=$BUILD_URL
RUN echo $COMMIT"|" >/var/share/html/commit
RUN date >>/var/share/html/commit
RUN echo "|" >>/var/share/html/commit
RUN echo $BUILD_URL"|" >>/var/share/html/commit
RUN echo $REPO_URL >>/var/share/html/commit
