"""Added account table

Revision ID: a0a5e59b97ec
Revises: 
Create Date: 2021-11-16 09:10:24.826095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0a5e59b97ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proc1_jobs_next_run_time', table_name='proc1_jobs')
    op.drop_table('proc1_jobs')
    op.drop_index('ix_proc2_jobs_next_run_time', table_name='proc2_jobs')
    op.drop_table('proc2_jobs')
    op.create_unique_constraint(None, 'call', ['id'])
    op.create_unique_constraint(None, 'event', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_constraint(None, 'call', type_='unique')
    op.create_table('proc2_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='proc2_jobs_pkey')
    )
    op.create_index('ix_proc2_jobs_next_run_time', 'proc2_jobs', ['next_run_time'], unique=False)
    op.create_table('proc1_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='proc1_jobs_pkey')
    )
    op.create_index('ix_proc1_jobs_next_run_time', 'proc1_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
